import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Diaspora News Reader",
  description:
    "Read Tamil news with English summaries and vocabulary learning, powered by Cohere Aya.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preconnect"
          href="https://fonts.googleapis.com"
        />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+Tamil:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="min-h-screen bg-stone-50 text-stone-900">
        <header className="border-b border-stone-200 bg-white">
          <div className="mx-auto max-w-3xl px-4 py-5">
            <a href="/" className="text-lg font-semibold tracking-tight">
              Diaspora News Reader
            </a>
            <p className="mt-1 text-sm text-stone-600">
              Tamil headlines, English summaries, vocabulary in context.
            </p>
          </div>
        </header>
        <main className="mx-auto max-w-3xl px-4 py-8">{children}</main>
        <footer className="mx-auto max-w-3xl px-4 pb-10 pt-4 text-xs text-stone-500">
          Summaries generated by Cohere Aya Expanse. Article text and links remain the property of
          their publishers.
        </footer>
      </body>
    </html>
  );
}
